// Copyright 2026 Alibaba Group Holding Ltd..
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/**
 * NOTE: The session-related path types and operations in this file (e.g. /session, runInSession)
 * are generated from the execd OpenAPI spec. They are not the recommended runtime entry point.
 * Use `sandbox.commands.createSession()`, `sandbox.commands.runInSession()`, and
 * `sandbox.commands.deleteSession()` instead.
 */
export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check endpoint
         * @description Performs a simple health check to verify that the server is running and responsive.
         *     Returns HTTP 200 OK status if the server is healthy. This endpoint is typically used
         *     by load balancers, monitoring systems, and orchestration platforms (like Kubernetes)
         *     to check service availability.
         */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/code/contexts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active code execution contexts
         * @description Lists all active/available code execution contexts.
         *     If `language` is provided, only contexts under that language/runtime are returned.
         */
        get: operations["listContexts"];
        put?: never;
        post?: never;
        /**
         * Delete all contexts under a language
         * @description Deletes all existing code execution contexts under the specified `language`/runtime.
         *     This is a bulk operation intended for code-interpreter context cleanup.
         */
        delete: operations["deleteContextsByLanguage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/code/contexts/{context_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a code execution context by id
         * @description Retrieves the details of an existing code execution context (session) by id.
         *     Returns the context ID, language, and any associated metadata.
         */
        get: operations["getContext"];
        put?: never;
        post?: never;
        /**
         * Delete a code execution context by id
         * @description Deletes an existing code execution context (session) by id.
         *     This should terminate the underlying context thread/process and release resources.
         */
        delete: operations["deleteContext"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/code/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create code execution context
         * @description Creates a new code execution environment and returns a session ID that can be used
         *     for subsequent code execution requests. The context maintains state across multiple
         *     code executions within the same session.
         */
        post: operations["createCodeContext"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute code in context
         * @description Executes code using Jupyter kernel in a specified execution context and streams
         *     the output in real-time using SSE (Server-Sent Events). Supports multiple programming
         *     languages (Python, JavaScript, etc.) and maintains execution state within the session.
         *     Returns execution results, output streams, execution count, and any errors.
         */
        post: operations["runCode"];
        /**
         * Interrupt code execution
         * @description Interrupts the currently running code execution in the specified context.
         *     This sends a signal to terminate the execution process and releases associated resources.
         */
        delete: operations["interruptCode"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create bash session (create_session)
         * @description Creates a new bash session and returns a session ID for subsequent run_in_session requests.
         *     The session maintains shell state (e.g. working directory, environment) across multiple
         *     code executions. Request body is optional; an empty body uses default options (no cwd override).
         */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/{sessionId}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run command in bash session (run_in_session)
         * @description Executes a shell command in an existing bash session and streams the output in real-time via SSE
         *     (Server-Sent Events). The session must have been created by create_session. Supports
         *     optional working directory override and timeout (milliseconds).
         */
        post: operations["runInSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete bash session (delete_session)
         * @description Deletes an existing bash session by ID. Terminates the underlying shell process
         *     and releases resources. The session ID must have been returned by create_session.
         */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute shell command
         * @description Executes a shell command and streams the output in real-time using SSE (Server-Sent Events).
         *     The command can run in foreground or background mode. The response includes stdout, stderr,
         *     execution status, and completion events.
         *     Optionally specify `timeout` (milliseconds) to enforce a maximum runtime; the server will
         *     terminate the process when the timeout is reached. You can also pass `uid`/`gid` to run
         *     with specific user/group IDs, and `envs` to inject environment variables.
         */
        post: operations["runCommand"];
        /**
         * Interrupt command execution
         * @description Interrupts the currently running command execution in the specified context.
         *     This sends a signal to terminate the execution process and releases associated resources.
         */
        delete: operations["interruptCommand"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/command/status/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get command running status
         * @description Returns the current status of a command (foreground or background) by command ID.
         *     Includes running flag, exit code, error (if any), and start/finish timestamps.
         */
        get: operations["getCommandStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/command/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get background command stdout/stderr (non-streamed)
         * @description Returns stdout and stderr for a background (detached) command by command ID.
         *     Foreground commands should be consumed via SSE; this endpoint is intended for
         *     polling logs of background commands. Supports incremental reads similar to a file seek:
         *     pass a starting line via query to fetch output after that line and receive the latest
         *     tail cursor for the next poll. When no starting line is provided, the full logs are returned.
         *     Response body is plain text so it can be rendered directly in browsers; the latest line index
         *     is provided via response header `EXECD-COMMANDS-TAIL-CURSOR` for subsequent incremental requests.
         */
        get: operations["getBackgroundCommandLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get file metadata
         * @description Retrieves detailed metadata for one or multiple files including permissions, owner,
         *     group, size, and modification time. Returns a map of file paths to their corresponding
         *     FileInfo objects.
         */
        get: operations["getFilesInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete files
         * @description Deletes one or multiple files from the sandbox. Only removes files, not directories.
         *     Use RemoveDirs for directory removal.
         */
        delete: operations["removeFiles"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change file permissions
         * @description Changes permissions (mode), owner, and group for one or multiple files.
         *     Accepts a map of file paths to permission settings including octal mode,
         *     owner username, and group name.
         */
        post: operations["chmodFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/mv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rename or move files
         * @description Renames or moves one or multiple files to new paths. Can be used for both
         *     renaming within the same directory and moving to different directories.
         *     Target directory must exist.
         */
        post: operations["renameFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search for files
         * @description Searches for files matching a glob pattern within a specified directory and
         *     its subdirectories. Returns file metadata including path, permissions, owner,
         *     and group. Supports glob patterns like **, *.txt, etc. Default pattern is ** (all files).
         */
        get: operations["searchFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/replace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace file content
         * @description Performs text replacement in one or multiple files. Replaces all occurrences
         *     of the old string with the new string (similar to strings.ReplaceAll).
         *     Preserves file permissions. Useful for batch text substitution across files.
         *
         *     When `verbose=true` is set, the response includes per-file replacement counts.
         *     Without this parameter, the response body is empty (backward-compatible behavior).
         */
        post: operations["replaceContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload files to sandbox
         * @description Uploads one or multiple files to specified paths within the sandbox.
         *     Reads metadata and file content from multipart form parts in sequence.
         *     Each file upload consists of two parts: a metadata part (JSON) followed
         *     by the actual file part.
         */
        post: operations["uploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download file from sandbox
         * @description Downloads a file from the specified path within the sandbox. Supports HTTP
         *     range requests for resumable downloads and partial content retrieval.
         *     Returns file as octet-stream with appropriate headers.
         *
         *     When offset/limit query parameters are provided, the endpoint performs
         *     line-based reading and returns text/plain content instead. Line-based
         *     parameters are mutually exclusive with the Range header.
         */
        get: operations["downloadFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/directories/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List directory contents
         * @description Lists entries under a directory with optional depth control. By default,
         *     only immediate children are returned (`depth=1`). Set `depth` to a larger
         *     value to include descendants up to that many levels below `path`. The
         *     root directory itself is not included in the response.
         *
         *     Symbolic links are reported with `type=symlink` and are not traversed:
         *     the listing never descends into a link target, even when `depth` would
         *     otherwise allow it. For the same reason, when `path` itself resolves to
         *     a symbolic link the request is rejected with `400`; callers must pass
         *     the real directory path they want listed.
         *
         *     Entries are returned in lexical order by entry name within each
         *     directory. Descendants reported via `depth>1` follow their parent in
         *     the same lexical order, so a depth-2 listing yields stable, predictable
         *     output for file-browser style clients.
         */
        get: operations["listDirectory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/directories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create directories
         * @description Creates one or multiple directories with specified permissions. Creates parent
         *     directories as needed (similar to mkdir -p). Accepts a map of directory paths
         *     to permission objects.
         */
        post: operations["makeDirs"];
        /**
         * Delete directories
         * @description Recursively deletes one or multiple directories and all their contents.
         *     Similar to rm -rf. Use with caution as this operation cannot be undone.
         */
        delete: operations["removeDirs"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get system metrics
         * @description Retrieves current system resource metrics including CPU usage percentage,
         *     CPU core count, total memory, used memory, and timestamp. Provides a snapshot
         *     of system resource utilization at the time of request.
         */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/watch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Watch system metrics in real-time
         * @description Streams system resource metrics in real-time using Server-Sent Events (SSE).
         *     Updates are sent every second, providing continuous monitoring of CPU usage,
         *     memory usage, and other system metrics. The connection remains open until
         *     the client disconnects.
         */
        get: operations["watchMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request to create a bash session (optional body; empty treated as defaults) */
        CreateSessionRequest: {
            /**
             * @description Working directory for the session (optional)
             * @example /workspace
             */
            cwd?: string;
        };
        /** @description Response for create_session */
        CreateSessionResponse: {
            /**
             * @description Unique session ID for run_in_session and delete_session
             * @example session-abc123
             */
            session_id: string;
        };
        /** @description Request to run a command in an existing bash session */
        RunInSessionRequest: {
            /**
             * @description Shell command to execute in the session
             * @example echo "Hello"
             */
            command: string;
            /**
             * @description Working directory override for this run (optional)
             * @example /workspace
             */
            cwd?: string;
            /**
             * Format: int64
             * @description Maximum execution time in milliseconds (optional; server may not enforce if omitted)
             * @example 30000
             */
            timeout?: number;
        };
        /** @description Request to create a code execution context */
        CodeContextRequest: {
            /**
             * @description Execution runtime (python, bash, java, etc.)
             * @example python
             */
            language?: string;
        };
        /** @description Code execution context with session identifier */
        CodeContext: {
            /**
             * @description Unique session identifier returned by CreateContext
             * @example session-abc123
             */
            id?: string;
            /**
             * @description Execution runtime
             * @example python
             */
            language: string;
        };
        /** @description Request to execute code in a context */
        RunCodeRequest: {
            context?: components["schemas"]["CodeContext"];
            /**
             * @description Source code to execute
             * @example import numpy as np
             *     result = np.array([1, 2, 3])
             *     print(result)
             */
            code: string;
        };
        /** @description Request to execute a shell command */
        RunCommandRequest: {
            /**
             * @description Shell command to execute
             * @example ls -la /workspace
             */
            command: string;
            /**
             * @description Working directory for command execution
             * @example /workspace
             */
            cwd?: string;
            /**
             * @description Whether to run command in detached mode
             * @default false
             * @example false
             */
            background: boolean;
            /**
             * Format: int64
             * @description Maximum allowed execution time in milliseconds before the command is forcefully terminated by the server. If omitted, the server will not enforce any timeout.
             * @example 60000
             */
            timeout?: number;
            /**
             * Format: int32
             * @description Unix user ID used to run the command. If `gid` is provided, `uid` is required.
             * @example 1000
             */
            uid?: number;
            /**
             * Format: int32
             * @description Unix group ID used to run the command. Requires `uid` to be provided.
             * @example 1000
             */
            gid?: number;
            /**
             * @description Environment variables injected into the command process.
             * @example {
             *       "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
             *       "PYTHONUNBUFFERED": "1"
             *     }
             */
            envs?: {
                [key: string]: string;
            };
        };
        /** @description Command execution status (foreground or background) */
        CommandStatusResponse: {
            /**
             * @description Command ID returned by RunCommand
             * @example cmd-abc123
             */
            id?: string;
            /**
             * @description Original command content
             * @example ls -la
             */
            content?: string;
            /**
             * @description Whether the command is still running
             * @example false
             */
            running?: boolean;
            /**
             * Format: int32
             * @description Exit code if the command has finished
             * @example 0
             */
            exit_code?: number | null;
            /**
             * @description Error message if the command failed
             * @example permission denied
             */
            error?: string;
            /**
             * Format: date-time
             * @description Start time in RFC3339 format
             * @example 2025-12-22T09:08:05Z
             */
            started_at?: string;
            /**
             * Format: date-time
             * @description Finish time in RFC3339 format (null if still running)
             * @example 2025-12-22T09:08:09Z
             */
            finished_at?: string | null;
        };
        /** @description Server-sent event for streaming execution output */
        ServerStreamEvent: {
            /**
             * @description Event type for client-side handling
             * @example stdout
             * @enum {string}
             */
            type?: "init" | "status" | "error" | "stdout" | "stderr" | "result" | "execution_complete" | "execution_count" | "ping";
            /**
             * @description Textual data for status, init, and stream events
             * @example Hello, World!
             */
            text?: string;
            /**
             * @description Cell execution number in the session
             * @example 1
             */
            execution_count?: number;
            /**
             * Format: int64
             * @description Execution duration in milliseconds
             * @example 150
             */
            execution_time?: number;
            /**
             * Format: int64
             * @description When the event was generated (Unix milliseconds)
             * @example 1700000000000
             */
            timestamp?: number;
            /**
             * @description Execution output in various MIME types (e.g., "text/plain", "text/html")
             * @example {
             *       "text/plain": "4"
             *     }
             */
            results?: {
                [key: string]: unknown;
            };
            /** @description Execution error details if an error occurred */
            error?: {
                /**
                 * @description Error name/type
                 * @example NameError
                 */
                ename?: string;
                /**
                 * @description Error value/message
                 * @example name 'undefined_var' is not defined
                 */
                evalue?: string;
                /**
                 * @description Stack trace lines
                 * @example [
                 *       "Traceback (most recent call last):",
                 *       "  File \"<stdin>\", line 1, in <module>",
                 *       "NameError: name 'undefined_var' is not defined"
                 *     ]
                 */
                traceback?: string[];
            };
        };
        /** @description File metadata including path and permissions */
        FileInfo: {
            /**
             * @description Absolute file path
             * @example /workspace/file.txt
             */
            path: string;
            /**
             * @description Entry type
             * @example file
             * @enum {string}
             */
            type?: "file" | "directory" | "symlink" | "other";
            /**
             * Format: int64
             * @description File size in bytes
             * @example 2048
             */
            size: number;
            /**
             * Format: date-time
             * @description Last modification time
             * @example 2025-11-16T14:30:45Z
             */
            modified_at: string;
            /**
             * Format: date-time
             * @description File creation time
             * @example 2025-11-16T14:30:45Z
             */
            created_at: string;
            /**
             * @description File owner username
             * @example admin
             */
            owner: string;
            /**
             * @description File group name
             * @example admin
             */
            group: string;
            /**
             * @description File permissions in octal format
             * @example 755
             */
            mode: number;
        };
        /** @description File ownership and mode settings */
        Permission: {
            /**
             * @description Owner username
             * @example root
             */
            owner?: string;
            /**
             * @description Group name
             * @example root
             */
            group?: string;
            /**
             * @description Permission mode in octal format (e.g., 644, 755)
             * @default 755
             * @example 755
             */
            mode: number;
        };
        /** @description File metadata for upload operations */
        FileMetadata: {
            /**
             * @description Target file path
             * @example /workspace/upload.txt
             */
            path?: string;
            /**
             * @description File owner
             * @example admin
             */
            owner?: string;
            /**
             * @description File group
             * @example admin
             */
            group?: string;
            /**
             * @description File permissions in octal
             * @example 755
             */
            mode?: number;
        };
        /** @description File rename/move operation */
        RenameFileItem: {
            /**
             * @description Source file path
             * @example /workspace/old.txt
             */
            src: string;
            /**
             * @description Destination file path
             * @example /workspace/new.txt
             */
            dest: string;
        };
        /** @description Content replacement operation */
        ReplaceFileContentItem: {
            /**
             * @description String to be replaced (must not be empty)
             * @example localhost
             */
            old: string;
            /**
             * @description Replacement string
             * @example 0.0.0.0
             */
            new: string;
        };
        /** @description Result of a content replacement operation on a single file */
        ReplaceFileContentResult: {
            /**
             * @description Number of occurrences replaced. 0 means oldContent was not found in the file.
             * @example 1
             */
            replacedCount: number;
        };
        /** @description System resource usage metrics */
        Metrics: {
            /**
             * Format: float
             * @description Number of CPU cores
             * @example 4
             */
            cpu_count: number;
            /**
             * Format: float
             * @description CPU usage percentage
             * @example 45.5
             */
            cpu_used_pct: number;
            /**
             * Format: float
             * @description Total memory in MiB
             * @example 8192
             */
            mem_total_mib: number;
            /**
             * Format: float
             * @description Used memory in MiB
             * @example 4096
             */
            mem_used_mib: number;
            /**
             * Format: int64
             * @description Timestamp when metrics were collected (Unix milliseconds)
             * @example 1700000000000
             */
            timestamp: number;
        };
        /** @description Standard error response format */
        ErrorResponse: {
            /**
             * @description Error code for programmatic handling
             * @example INVALID_REQUEST_BODY
             */
            code: string;
            /**
             * @description Human-readable error message
             * @example error parsing request, MAYBE invalid body format
             */
            message: string;
        };
    };
    responses: {
        /** @description Invalid request body format or missing required fields */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "INVALID_REQUEST_BODY",
                 *       "message": "error parsing request, MAYBE invalid body format"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description File or resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "FILE_NOT_FOUND",
                 *       "message": "file not found"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Runtime server error during operation */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "RUNTIME_ERROR",
                 *       "message": "error running code execution"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is alive and healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listContexts: {
        parameters: {
            query: {
                /**
                 * @description Filter contexts by execution runtime (python, bash, java, etc.)
                 * @example python
                 */
                language: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of active contexts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeContext"][];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteContextsByLanguage: {
        parameters: {
            query: {
                /**
                 * @description Target execution runtime whose contexts should be deleted
                 * @example python
                 */
                language: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contexts deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getContext: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Session/context id to get
                 * @example session-abc123
                 */
                context_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Context details retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeContext"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteContext: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Session/context id to delete
                 * @example session-abc123
                 */
                context_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Context deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createCodeContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeContextRequest"];
            };
        };
        responses: {
            /** @description Successfully created context with session ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeContext"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    runCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCodeRequest"];
            };
        };
        responses: {
            /** @description Stream of code execution events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ServerStreamEvent"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    interruptCode: {
        parameters: {
            query: {
                /**
                 * @description Session ID of the execution context to interrupt
                 * @example session-123
                 */
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Code execution successfully interrupted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Session created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    runInSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Session ID returned by create_session
                 * @example session-abc123
                 */
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunInSessionRequest"];
            };
        };
        responses: {
            /** @description Stream of execution events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ServerStreamEvent"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Session ID to delete
                 * @example session-abc123
                 */
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    runCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCommandRequest"];
            };
        };
        responses: {
            /** @description Stream of command execution events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ServerStreamEvent"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    interruptCommand: {
        parameters: {
            query: {
                /**
                 * @description Session ID of the execution context to interrupt
                 * @example session-456
                 */
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Command execution successfully interrupted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCommandStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Command ID returned by RunCommand
                 * @example cmd-abc123
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Command status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandStatusResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getBackgroundCommandLogs: {
        parameters: {
            query?: {
                /**
                 * @description Optional 0-based line cursor (behaves like a file seek). When provided, only
                 *     stdout/stderr lines after this line are returned. The response includes the
                 *     latest line index (`cursor`) so the client can request incremental output
                 *     on subsequent calls. If omitted, the full log is returned.
                 * @example 120
                 */
                cursor?: number;
            };
            header?: never;
            path: {
                /**
                 * @description Command ID returned by RunCommand
                 * @example cmd-abc123
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Command output (plain text) and status metadata via headers */
            200: {
                headers: {
                    /** @description Highest available 0-based line index after applying the request cursor (use as the next cursor for incremental reads) */
                    "EXECD-COMMANDS-TAIL-CURSOR"?: number;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example line1
                     *     line2
                     *     warn: something on stderr
                     */
                    "text/plain": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getFilesInfo: {
        parameters: {
            query: {
                /** @description File path(s) to get info for (can be specified multiple times) */
                path: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Map of file paths to FileInfo objects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["FileInfo"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    removeFiles: {
        parameters: {
            query: {
                /**
                 * @description File path(s) to delete (can be specified multiple times)
                 * @example [
                 *       "/workspace/temp.txt"
                 *     ]
                 */
                path: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Files deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    chmodFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "/workspace/script.sh": {
                 *         "owner": "admin",
                 *         "group": "admin",
                 *         "mode": 755
                 *       },
                 *       "/workspace/config.json": {
                 *         "owner": "admin",
                 *         "group": "admin",
                 *         "mode": 755
                 *       }
                 *     }
                 */
                "application/json": {
                    [key: string]: components["schemas"]["Permission"];
                };
            };
        };
        responses: {
            /** @description Permissions changed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    renameFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example [
                 *       {
                 *         "src": "/workspace/old_name.txt",
                 *         "dest": "/workspace/new_name.txt"
                 *       },
                 *       {
                 *         "src": "/workspace/file.py",
                 *         "dest": "/archive/file.py"
                 *       }
                 *     ]
                 */
                "application/json": components["schemas"]["RenameFileItem"][];
            };
        };
        responses: {
            /** @description Files renamed/moved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    searchFiles: {
        parameters: {
            query: {
                /** @description Root directory path to search in */
                path: string;
                /** @description Glob pattern to match files (default is **) */
                pattern?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of matching files with metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileInfo"][];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    replaceContent: {
        parameters: {
            query?: {
                /** @description When true, return per-file replacement counts in the response body. */
                verbose?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "/workspace/config.yaml": {
                 *         "old": "localhost:8080",
                 *         "new": "0.0.0.0:9090"
                 *       },
                 *       "/workspace/app.py": {
                 *         "old": "DEBUG = True",
                 *         "new": "DEBUG = False"
                 *       }
                 *     }
                 */
                "application/json": {
                    [key: string]: components["schemas"]["ReplaceFileContentItem"];
                };
            };
        };
        responses: {
            /**
             * @description Content replaced successfully. When `verbose=true`, returns per-file
             *     replacement counts. Otherwise, the response body is empty.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "/workspace/config.yaml": {
                     *         "replacedCount": 1
                     *       },
                     *       "/workspace/app.py": {
                     *         "replacedCount": 0
                     *       }
                     *     }
                     */
                    "application/json": {
                        [key: string]: components["schemas"]["ReplaceFileContentResult"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    uploadFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * @description JSON-encoded file metadata (FileMetadata object)
                     * @example {"path":"/workspace/file.txt","owner":"admin","group":"admin","mode":755}
                     */
                    metadata?: string;
                    /**
                     * Format: binary
                     * @description File to upload
                     */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description Files uploaded successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    downloadFile: {
        parameters: {
            query: {
                /**
                 * @description Absolute or relative path of the file to download
                 * @example /workspace/data.csv
                 */
                path: string;
                /**
                 * @description Starting line number (1-based) for line-based reading. Mutually exclusive with the Range header.
                 * @example 100
                 */
                offset?: number;
                /**
                 * @description Number of lines to return for line-based reading. Mutually exclusive with the Range header.
                 * @example 20
                 */
                limit?: number;
            };
            header?: {
                /**
                 * @description HTTP Range header for partial content requests. Mutually exclusive with offset/limit.
                 * @example bytes=0-1023
                 */
                Range?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description File content. Returns application/octet-stream for full or byte-range
             *     downloads, or text/plain for line-based reads (when offset/limit are provided).
             */
            200: {
                headers: {
                    /** @description Attachment header with filename (byte-range mode only) */
                    "Content-Disposition"?: string;
                    /** @description File size in bytes (byte-range mode only) */
                    "Content-Length"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                    "text/plain": string;
                };
            };
            /** @description Partial file content (when Range header is provided) */
            206: {
                headers: {
                    /** @description Range of bytes being returned */
                    "Content-Range"?: string;
                    /** @description Length of the returned range */
                    "Content-Length"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Requested range not satisfiable */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    listDirectory: {
        parameters: {
            query: {
                /**
                 * @description Directory path to list
                 * @example /workspace/project
                 */
                path: string;
                /**
                 * @description Maximum child depth to include. `1` lists immediate children only.
                 * @example 2
                 */
                depth?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of directory entries with metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "path": "/workspace/project/src",
                     *         "type": "directory",
                     *         "size": 0,
                     *         "modified_at": "2025-11-16T14:30:45Z",
                     *         "created_at": "2025-11-16T14:30:45Z",
                     *         "owner": "admin",
                     *         "group": "admin",
                     *         "mode": 755
                     *       },
                     *       {
                     *         "path": "/workspace/project/README.md",
                     *         "type": "file",
                     *         "size": 2048,
                     *         "modified_at": "2025-11-16T14:30:45Z",
                     *         "created_at": "2025-11-16T14:30:45Z",
                     *         "owner": "admin",
                     *         "group": "admin",
                     *         "mode": 644
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["FileInfo"][];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    makeDirs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "/workspace/project": {
                 *         "owner": "admin",
                 *         "group": "admin",
                 *         "mode": 755
                 *       },
                 *       "/workspace/logs": {
                 *         "owner": "admin",
                 *         "group": "admin",
                 *         "mode": 755
                 *       }
                 *     }
                 */
                "application/json": {
                    [key: string]: components["schemas"]["Permission"];
                };
            };
        };
        responses: {
            /** @description Directories created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    removeDirs: {
        parameters: {
            query: {
                /**
                 * @description Directory path(s) to delete (can be specified multiple times)
                 * @example [
                 *       "/workspace/temp"
                 *     ]
                 */
                path: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Directories deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current system metrics including CPU and memory usage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metrics"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    watchMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream of system metrics updated every second */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["Metrics"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
}
